# Array Creation

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr) 

[1 2 3 4 5]


In [3]:
arr=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [4]:
arr1=np.ones(4)
print(arr1)

[1. 1. 1. 1.]


In [5]:
arr1=np.ones((4,2),int)
print(arr1)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [6]:
arr1=np.ones((3,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arr2=np.empty(4)
print(arr2)

[2.12199579e-314 2.12199579e-314 2.12199579e-314 2.12199579e-314]


In [8]:
arr3=np.arange(1,4)
print(arr3)

[1 2 3]


In [9]:
arr4=np.concatenate([arr2,arr3])
print(arr4)

[2.12199579e-314 2.12199579e-314 2.12199579e-314 2.12199579e-314
 1.00000000e+000 2.00000000e+000 3.00000000e+000]


In [10]:
arr7=arr2.astype(int)
print(arr7)

[0 0 0 0]


In [11]:
arr8=np.zeros_like(arr4)
print(arr8)

[0. 0. 0. 0. 0. 0. 0.]


In [12]:
arr9=np.random.random((4,5))
print(arr9)

[[0.55345914 0.95959844 0.63750948 0.10446238 0.31730914]
 [0.92377439 0.07827377 0.97362665 0.01534577 0.59108442]
 [0.81217351 0.13223033 0.09738537 0.43923419 0.60760653]
 [0.55892673 0.32677399 0.27739445 0.69576084 0.65779929]]


In [13]:
l=[1,2,3,4,5]
arr10=np.array(l)
print(arr10)

[1 2 3 4 5]


In [14]:
arr11=np.linspace(5,20,5,dtype=float)
print(arr11)

[ 5.    8.75 12.5  16.25 20.  ]


In [15]:
arr12=np.logspace(1,5,5)
print(arr12)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


In [16]:
print(arr)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [17]:
print(arr.ndim)

2


In [18]:
print(np.ndim(arr))

2


In [19]:
print(arr.shape)

(3, 3)


In [20]:
print(arr.size)

9


In [21]:
print(arr.dtype)

int32


In [22]:
print(arr.itemsize)

4


In [23]:
print(arr.data)

In [24]:
print(arr.nbytes) 

36


In [25]:
print(arr[2])

[6 7 8]


In [26]:
print(arr[2,-2])

7


In [27]:
arr[2]=10
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [10 10 10]]


In [28]:
arr=np.array([1,2,3,4,5,6,7,8,9])

print (arr.shape)
print(arr)
arr1=arr.reshape(3,3)
print(arr1.shape)
print(arr1)

arr2=arr.reshape((3,3),order='c')
print(arr2)
arr2=arr.reshape((3,3),order='f')
print(arr2)

arr3=arr.flatten()
arr4=arr.ravel()
print(arr3);print(arr4)

(9,)
[1 2 3 4 5 6 7 8 9]
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


# ndarray Slicing

In [29]:
arr=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1:4])
print(arr[4:])
print(arr[:4])
print(arr[1:5:2])
print(arr[-3:-1])
print(arr[::2])
print(arr2[1,1:4])
print(arr2[0:2,2])
print(arr2[0:2,1:4])

[2 3 4]
[5]
[1 2 3 4]
[2 4]
[3 4]
[1 3 5]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [30]:
arr2[0,3:5]


array([4, 5])

# Advanced Indexing

In [35]:
arr=np.array([1,2,3,4,5])
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
list1=[1,2,-3]
print(arr[list1])
print(arr[[3,4,-4]])
y = arr1[[0,1,1], [0,1,4]] 
print(y)
y = arr1[1:3,[1,2]]
print(y)


[2 3 3]
[4 5 2]
[ 1  7 10]
[[ 7  8]
 [12 13]]


In [49]:
check=arr>3
print(check)
print(arr[check])
l=[0,1,0,1,0]
print(arr[l])

[False False False  True  True]
[4 5]
[1 2 1 2 1]


# Numpy methods

In [50]:
arr=np.array([1,2,3,4,5])
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
x=arr1.flatten() 
print(x)
x[4]=30
y=np.ravel(arr1) 
y[3]=20
print(arr1); print(x); print(y)
x.resize((3,5)) 
print(arr1)
print(arr1.swapaxes(1,0))
print(arr1.transpose())
print(arr1.T)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3 20  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 1  2  3  4 30  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3 20  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3 20  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [20  9 14]
 [ 5 10 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [20  9 14]
 [ 5 10 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [20  9 14]
 [ 5 10 15]]


In [51]:
arr=np.array([1,2,3,4,5])
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr1.dtype)
print(arr1.astype(float))
arr1[1,3]=0;arr1[0,3]=0
print(arr1.nonzero())
print(arr1)
arr1.argsort(axis=0)
print(arr1.argsort(axis=1))
arr1.sort(axis=1)
print(arr1)
print(arr.searchsorted(3))


int32
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 4, 0, 1, 2, 4, 0, 1, 2, 3, 4], dtype=int64))
[[ 1  2  3  0  5]
 [ 6  7  8  0 10]
 [11 12 13 14 15]]
[[3 0 1 2 4]
 [3 0 1 2 4]
 [0 1 2 3 4]]
[[ 0  1  2  3  5]
 [ 0  6  7  8 10]
 [11 12 13 14 15]]
2


# Iterating Arrays

In [53]:
arr=np.array([1,2,3,4,5])
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
for x in arr:
 print(x) 
for x in arr1:
 print(x) 
for x in arr1:
 for y in x:
  print(y) 
for x in np.nditer(arr1):
 print(x)

1
2
3
4
5
[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


# String Functions

In [55]:
np.char.add(['a','b'],['c','d'])


array(['ac', 'bd'], dtype='<U2')

In [56]:
np.char.multiply(['a','b'],3)

array(['aaa', 'bbb'], dtype='<U3')

# Array Operations

In [57]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print(arr2)
print(arr1+arr2)
print(np.add(arr1,arr2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [58]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1==arr2)
print(np.equal(arr1,arr2))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# Array Calculation Methods

In [59]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[-1.7,2.1,3.5],[4,-5,6],[7,8,-9]])
print(arr1.sum())
print(arr1.sum(axis=0))
print(arr1.sum(axis=1))
print(arr1.prod())
print(np.sin(arr2))
print(np.negative(arr2))
print(np.ceil(arr2))
print(np.minimum(arr1,arr2))

45
[12 15 18]
[ 6 15 24]
362880
[[-0.99166481  0.86320937 -0.35078323]
 [-0.7568025   0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825 -0.41211849]]
[[ 1.7 -2.1 -3.5]
 [-4.   5.  -6. ]
 [-7.  -8.   9. ]]
[[-1.  3.  4.]
 [ 4. -5.  6.]
 [ 7.  8. -9.]]
[[-1.7  2.   3. ]
 [ 4.  -5.   6. ]
 [ 7.   8.  -9. ]]


# Broadcasting

In [60]:
arr1 = np.array([[0],[10],[20],[30]])
arr2 = np.array([0,1,2])
print(arr1+arr2)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


# Conditional

In [61]:
arr1=np.array([[-1.7,2.1,3.5],[4,
-5,6],[7,8,-9]])
print(arr1>0)
print((arr1>2).sum())
print(np.where(arr1>3,'Yes','No'))


[[False  True  True]
 [ True False  True]
 [ True  True False]]
6
[['No' 'No' 'Yes']
 ['Yes' 'No' 'Yes']
 ['Yes' 'Yes' 'No']]


# Graphical

In [62]:
arr1 = np.random.randint(100, size =(50)) 
np.histogram(arr1, bins = [0, 10, 20, 30, 40,50, 60, 70, 80, 90, 100])

(array([4, 8, 3, 7, 7, 6, 3, 7, 2, 3], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))